using System;

// public  class Cat
// {
//     public Cat() {
//     }
//
//     public Cat(string name) {
//         Name = name;
//     }
//
//     public string Name { get; set; }
//
//     public string Shout() {
//         return "I'm " + Name + ", mewo~";
//     }
// }
//
// public  class Dog
// {
//     public Dog() {
//     }
//
//     public Dog(string name) {
//         Name = name;
//     }
//
//     public string Name { get; set; }
//
//     public string Shout() {
//         return "I'm " + Name + ", wowww~";
//     }
// }

public class LECTURE1_1
{
    // private static void Main(string[] args) {
    //     Cat cat1 = new Cat();
    //     Dog dog1 = new Dog();
    //
    //     Console.WriteLine(cat1.Shout());
    //     Console.WriteLine(dog1.Shout());
    // }
}